port: 4222
http_port: 8222
jetstream { store_dir: /data/jetstream }
authorization {
  users: [
    { user: admin, password: $NATS_ADMIN_PASSWORD,
      permissions: { publish: "$JS.API.>", subscribe: "_INBOX.admin.>" } },
    { user: business_france, password: $NATS_BF_PASSWORD,
      permissions: { publish: "offers.business_france.v1", subscribe: "_INBOX.business_france.>" } },
    { user: wttj, password: $NATS_WTTJ_PASSWORD,
      permissions: { publish: "offers.wttj.v1", subscribe: "_INBOX.wttj.>" } },
    { user: notifications, password: $NATS_NOTIFICATIONS_PASSWORD,
      permissions: {
        publish: ["$JS.API.CONSUMER.INFO.OFFERS.notifications",
                  "$JS.API.CONSUMER.MSG.NEXT.OFFERS.notifications",
                  "$JS.ACK.OFFERS.notifications.>"],
        subscribe: "_INBOX.notifications.>"
      } }
  ]
}
