[project]
name = "bovie-notification-intake"
version = "0.4.0"
requires-python = ">=3.13"
description = "BoVIE notification-intake"
dependencies = [
    "click>=8.1.8",
    "loguru>=0.7.3",
    "sqlalchemy>=2.0,<2.1",
    "nats-py>=2.10,<3",
    "bovie-contracts",
    "bovie-database",
    "bovie-notification-store",
    "bovie-messaging",
    "bovie-runtime"
]

[project.scripts]
notification-intake = "notification_intake.main:main"

[tool.uv.build-backend]
module-name = "notification_intake"

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
