[project]
name = "bovie-broker-setup"
version = "0.4.0"
requires-python = ">=3.13"
description = "BoVIE broker-setup"
dependencies = [
    "click>=8.1.8",
    "nats-py>=2.10,<3",
    "bovie-messaging",
    "bovie-runtime"
]

[project.scripts]
broker-setup = "broker_setup.main:main"

[tool.uv.build-backend]
module-name = "broker_setup"

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
